a=input("Enter the 1st integer collection:")
a=list(map(int,a.split(",")))
print(a)
b=input("Enter the 2nd integer collection:")
b=list(map(int,b.split(",")))
print(b)
print("Lists are same length:",len(a)==len(b))
print("Sums are equal:",sum(a)==sum(b))
print("Values occur in both:",bool(set(a)&set(b)))
